### ISSUE TITLE
[feature request] add "display" setting like in Blender 2.7x

### ISSUE THREAD

**Issue by zocker-160** [Mitsuma/Blender2.8-RenderButton#1]
It would be nice having the "old" setting of the [render panel](https://docs.blender.org/manual/en/2.79/render/output/render_panel.html) as well, where you can change the way how the renders are displayed.

afaik it is not possible to change this setting in Blender 2.8.

**Comment by Mitsuma** [comment]
![blender_2019-03-01_16-46-33](https://user-images.githubusercontent.com/8568089/53649036-9f9e4000-3c41-11e9-8231-07540ab4d92d.png)
You can actually change the setting, they also put it where the render buttons went.

I will look into it but I can't promise anything, this current one was already just thrown together from things I found, so I would have to look up how I make the rest happen, if its still possible to set those things with simple python like the render buttons.

**Comment by Mitsuma** [comment]
Was actually easier then I thought, seems nothing changed under the hood, so I could just add the Display part.

![blender_2019-03-01_17-12-40](https://user-images.githubusercontent.com/8568089/53650650-49cb9700-3c45-11e9-94a8-515397f0c22f.png)

Newest version is under releases or just download the file from the source here.

**Comment by zocker-160** [comment]
thank you!
